version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: ../
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      #- swagger-ui_value:/app/templates/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../templates/:/usr/share/nginx/html/api/templates/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  #swagger-ui_value:
