# Generated by Django 3.2.16 on 2022-11-22 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AlterField(
            model_name='instructions',
            name='axis',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='distance',
            field=models.IntegerField(verbose_name='Пройденное расстояние'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который создал указание'),
        ),
        migrations.AlterField(
            model_name='station',
            name='date_broken',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата поломки'),
        ),
        migrations.AlterField(
            model_name='station',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название станции'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(choices=[('running', 'Работает'), ('broken', 'Сломана')], default='running', max_length=30, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='StationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='api.instructions')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='api.station')),
            ],
        ),
    ]
