# Generated by Django 3.2.16 on 2022-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='x',
            field=models.IntegerField(default=100, editable=False),
        ),
        migrations.AddField(
            model_name='station',
            name='y',
            field=models.IntegerField(default=100, editable=False),
        ),
        migrations.AddField(
            model_name='station',
            name='z',
            field=models.IntegerField(default=100, editable=False),
        ),
    ]
