# Generated by Django 3.2.16 on 2022-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221127_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='z',
            field=models.IntegerField(default=100),
        ),
    ]
