# Generated by Django 3.2.16 on 2022-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221127_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationcoordinates',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='stationcoordinates',
            name='station',
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.DeleteModel(
            name='StationCoordinates',
        ),
    ]
