# Generated by Django 3.2.16 on 2022-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221127_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='axis',
            field=models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=5, verbose_name='Ось'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='distance',
            field=models.IntegerField(verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.IntegerField(default=100, verbose_name='Координата x'),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.IntegerField(default=100, verbose_name='Координата y'),
        ),
        migrations.AlterField(
            model_name='station',
            name='z',
            field=models.IntegerField(default=100, verbose_name='Координата z'),
        ),
    ]
